name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
    if: github.event.pull_request.merged == true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6
        with:
          version: 10


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20'

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mcpsshub:latest
